### ISSUE TITLE
Bluetooth pref panel and menu icon inconsistent on startup

### ISSUE THREAD

**Issue by jdloft** [tylernguyen/x1c6-hackintosh#109] opened 2020-12-19 17:50 UTC
**Describe the bug**
On initial startup bluetooth pref panel takes a minute or so to load and the menu bar icon shows it as off. Once the pref panel has loaded bluetooth peripherals can be connected but the menu bar still shows it as being off.

**To Reproduce**
1. Start machine
2. Verify bluetooth menu bar shows bluetooth as off
3. Open system preferences and verify bluetooth pref panel is missing
4. Wait 1-2 minutes
5. Verify bluetooth pref panel is loaded and peripheral (in my case, a bluetooth mouse)
6. Verify bluetooth menu icon still shows bluetooth as off
7. Sleep machine, log out or switch users
8. Verify bluetooth menu icon is now consistent with bluetooth state

**Expected behavior**
Bluetooth should be loaded on boot, but more importantly, menu bar should always be consistent with real bluetooth state.

**Screenshots**

After initial boot: (notice bluetooth pref panel missing and menu bar bluetooth icon shows bluetooth as off)
![Screen Shot 2020-12-19 at 12 29 27 PM](https://user-images.githubusercontent.com/8332322/102695723-1cbfee00-41f7-11eb-8840-fb701c540ecf.png)

After wait, opening bluetooth pref panel and connecting mouse:
![Screen Shot 2020-12-19 at 12 33 22 PM](https://user-images.githubusercontent.com/8332322/102695726-2b0e0a00-41f7-11eb-87af-dbc662fb1262.png)

After sleeping machine and waking it again:
![Screen Shot 2020-12-19 at 12 37 20 PM](https://user-images.githubusercontent.com/8332322/102695741-3bbe8000-41f7-11eb-87fc-693544b36044.png)

**Appropriate boot and/or debug logs**
Let me know what logs should be attached and I'll get them. I don't really know how to start debugging this.

**If you do cannot provide boot and/or debug logs, please provide a ZIP of your EFI**
Verified this behavior with the exact same ACPI patches included in this repository and the same config.plist in EFI-OpenCore except the PlatformInfo section (which I wouldn't include attached for privacy; so essentially it's vanilla).

I believe this is a new issue; I didn't have it as of a few weeks ago. I keep relatively up-to-date with this repository. Also, I noticed this issue after replacing my SSD (the new one is a WD SN750). That may not be related to this since I have reinstalled macOS multiple times and have verified this issue with both the old and new SSD.

Model: 20KG
Wifi/Bluetooth: BCM94360CS2

**Comment by H15teve** [comment] 2020-12-21 02:45
Same issue after the update to latest BrcmPatchRAM. My card is DW1830

**Comment by erdemoney** [comment] 2020-12-21 03:28
Just updated to the last EFI and started having the same issue on boot. My card is the  BCM94360CS2 as well.

**Comment by tylernguyen** [comment] 2020-12-21 05:21
@jdloft 

What macOS version are you on?
If this issue appeared after replacing your SSD, I would check your card's physical connection, especially with the adapter.

**Comment by jdloft** [comment] 2020-12-21 16:09
I'm on macOS 11.1. I noticed this problem after replacing the SSD, but swapped back the SSD to see if it was still a problem. I noticed it on both, so I believe it was just a coincidence.

**Comment by Naplesoul** [comment] 2020-12-26 04:00
The same problem with DW1560 card. Problem solved after performing a clean snapshot. But the trackpoint doesn’t work after the clean snapshot. I tried to make the ACPI loading order the same as the plist provided, and the Bluetooth problem shows up again. It looks like the ACPI loading order has some problems. I’m new to hackintosh, and I am not sure with it.

**Comment by tylernguyen** [comment] 2020-12-26 13:18
Hm..

The problem is I can't replicate this issue so it's quite hard for me to figure out what's wrong.

For those that have this issue, can you please:

1. Upgrade to the latest commit.
2. Install OpenCore debug files
3. Add debug arguments to `config.plist`https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/debug.html#file-swaps
4. Post OpenCore boot logs for when Bluetooth does not show.

**Comment by tylernguyen** [comment] 2020-12-29 18:09
@erdemoney mentioned that this issue was resolved after a clean install. Please check.

**Comment by jdloft** [comment] 2021-01-01 18:55
Problem persists after full clean reinstall.

**Comment by tylernguyen** [comment] 2021-01-01 19:14
> 
> 
> Problem persists after full clean reinstall.

Have you check the physical connection on the card? Perhaps it's shaky?

**Comment by jdloft** [comment] 2021-01-01 21:30
I managed to narrow the issue down to the modifications to `SSDT-XHC1` in 252233c. I'm not that well versed in ACPI, so I have no idea what to look for. I'm not even sure why a modification to the XHCI stuff would affect the bluetooth menu.

**Comment by tylernguyen** [comment] 2021-01-02 01:09
@jdloft 

The thing is I can't replicate that issue, which leaves me to believe it's a setup issue. What does your EFI look like?

**Comment by jdloft** [comment] 2021-01-02 04:30
Yeah, it's funny because my setup is pretty vanilla. I've just been copying the OC dir from EFI-OpenCore to my ESP and changing the PlatformInfo section in the config.plist and I've reinstalled 3 or 4 times. I've swapped out SSDT-XHC1.aml (compiled by me and the precompiled one in this repo) before and after 252233c and it always works and then doesn't with the newer one. BIOS is modded.

**Comment by jdloft** [comment] 2021-01-02 16:25
Could any of the other people that were seeing this issue try the fix above (move the ACPI entry for XHC1 above DSB0)? Thanks!

**Comment by finisi** [comment] 2021-01-03 11:49
> Could any of the other people that were seeing this issue try the fix above (move the ACPI entry for XHC1 above DSB0)? Thanks!

I confirm that moving entry for XHC1 before DSB0 solves the issue with Bluetooth icon showing and functioning correctly. Works after waking up as well.

**Comment by tylernguyen** [comment] 2021-01-03 18:42
> > Could any of the other people that were seeing this issue try the fix above (move the ACPI entry for XHC1 above DSB0)? Thanks!
> 
> 
> 
> I confirm that moving entry for XHC1 before DSB0 solves the issue with Bluetooth icon showing and functioning correctly. Works after waking up as well.

Sounds good. I'll review the fix and push it on the next update.

**Comment by tylernguyen** [comment] 2021-01-05 22:50
Fixed as of 7db7a17

**Closed by tylernguyen** 2021-01-05 22:50 UTC
