### ISSUE TITLE
Trackpad and trackpoint missing after modern sleep

### ISSUE THREAD

**Issue by exp13579** [tylernguyen/x1c6-hackintosh#108] opened 2020-12-02 10:33 UTC
**Describe the bug**
I am using x1 carbon 6th with the latest EFI config. However, I found that when I closed the lid, waited for 30min, and when I reopened the lid, the trackpad and trackpoint were not functioning, and the mouse cursor was disappeared from the screen until I plugged a external mouse.

What is more strange is that the problem continues even after I reboot the machine, Mac or Windows, the problem consists. 

The trackpad and trackpoint will only back to normal when I shutdown the machine and reboot it. 

I have generated the SMBIOS, updated the CpuFriendFriend (since I have i7-8550U). The NVME SSD the Mac installed is Intel 760p.

Here is  my EFI:

[EFI.zip](https://github.com/tylernguyen/x1c6-hackintosh/files/5628592/EFI.zip)

**Comment by tylernguyen** [comment] 2020-12-02 18:45
@exp13579 
This is the first I've heard of this issue. If it happens in Windows too, I doubt it's a macOS issue. I reckon it's hardware/machine related.

**Comment by lubixxx96** [comment] 2020-12-02 19:15
Had a similar issue.
It started the same way, trackpad/trackpoint stopped working after long sleep.
Then it stopped working completely, sometimes disabling the internal battery in bios helped, but only for a while.
The final state was completely dead trackpoint and trackpad, in all OSs, even bios diagnostics did not recognize them.

I had a luck for a good guys in lenovo service center, they replaced the trackpad - didnt work, so they also replaced motherboard, still no success so they replaced also whole top cover with keyboard and trackpoint.
After that it was fine again.

But not for long....same issue started to appear and same story...completely dead trackpoint and trackpad after a few weeks.

They replaced all 3 parts again and I decided to ditch the Hackintosh to see if it happens again.
Only few weeks now but so far no issue.
I didnt want to believe that OS can be responsible for that, but it looks like it may be...

**Comment by tylernguyen** [comment] 2020-12-02 19:21
@lubixxx96 

I've been hackintoshing on this machine for over two years now and it's been very stable. What you are describing above seems to be hardware issues particular to your own machine/batch. Will close this issue now as it's not repo related and I cannot investigate without particular evidence or means to reproduce.

**Closed by tylernguyen** 2020-12-02 19:21 UTC

**Comment by exp13579** [comment] 2020-12-07 12:47
I further found that if I switched to Hibernation 25 for battery mode and non-sleep for adapter mode, the symptom did not show again. So maybe it is related to ssdt-sleep?
